### ISSUE TITLE
add to the krew plugin index?

### ISSUE THREAD

**Issue by joemiller** [micnncim/kubectl-reap#28]
Great plugin! Have you considered submitting it to the [krew](https://github.com/kubernetes-sigs/krew) plugin [index](https://github.com/kubernetes-sigs/krew-index) ?

**Comment by micnncim** [comment]
@joemiller Thank you! Yeah, I have considered submitting this plugin to krew-index and am going to do so after a little more improvement (e.g., supporting more resources and enhancing test coverage).

**Comment by micnncim** [comment]
Now that https://github.com/kubernetes-sigs/krew-index/pull/793 has been merged, we can install this plugin via Krew:

```
$ kubectl krew install reap
```
