### ISSUE TITLE
exclude secret/configmap used in replicaset (for deployment rollback)

### ISSUE THREAD

**Issue by sumitsaiwal** [micnncim/kubectl-reap#96]
can we please add some exclusion feature for secret/configmaps which are referred in replica sets, which might be helpful while rolling back a deployment. And replicaset are automatically getting cleaned up based on `.spec.revisionHistoryLimit` of Deployment.

**Comment by micnncim** [comment]
Sorry fir the late reply. That would make sense. I'm going to implement it 👍
